config/routes.rb
Mjservices::Application.routes.draw do
  resources :bill_pays

  resources :bills

  devise_for :users

  resources :bill_accounts

  resources :bill_services

end

app/models/bill_pay.rb
class BillPay < ActiveRecord::Base
  attr_accessible :bill_amount, :bill_due_date, :bill_id, :bill_no, :name
  attr_accessible :photo
  #relations
  attr_accessible :bill_id
  belongs_to :bill
  
  has_attached_file :photo, :styles => { :small => "150x150>" },
                  :url  => "/assets/bill_pays/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/bill_pays/:id/:style/:basename.:extension"

	validates_attachment_presence :photo
	validates_attachment_size :photo, :less_than => 10.megabytes
	validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

end

app/controllers/bill_pays_controller.rb
class BillPaysController < ApplicationController
  # GET /bill_pays
  # GET /bill_pays.json
  def index
    @bill_pays = BillPay.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bill_pays }
    end
  end

  # GET /bill_pays/1
  # GET /bill_pays/1.json
  def show
    @bill_pay = BillPay.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bill_pay }
    end
  end

  # GET /bill_pays/new
  # GET /bill_pays/new.json
  def new
    @bill_pay = BillPay.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bill_pay }
    end
  end

  # GET /bill_pays/1/edit
  def edit
    @bill_pay = BillPay.find(params[:id])
  end

  # POST /bill_pays
  # POST /bill_pays.json
  def create
    @bill_pay = BillPay.new(params[:bill_pay])

    respond_to do |format|
      if @bill_pay.save
        format.html { redirect_to @bill_pay, notice: 'Bill pay was successfully created.' }
        format.json { render json: @bill_pay, status: :created, location: @bill_pay }
      else
        format.html { render action: "new" }
        format.json { render json: @bill_pay.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bill_pays/1
  # PUT /bill_pays/1.json
  def update
    @bill_pay = BillPay.find(params[:id])

    respond_to do |format|
      if @bill_pay.update_attributes(params[:bill_pay])
        format.html { redirect_to @bill_pay, notice: 'Bill pay was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bill_pay.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bill_pays/1
  # DELETE /bill_pays/1.json
  def destroy
    @bill_pay = BillPay.find(params[:id])
    @bill_pay.destroy

    respond_to do |format|
      format.html { redirect_to bill_pays_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bill_pays_helper.rb
module BillPaysHelper
end

app/views/bill_pays/_form.html.erb
<%= simple_form_for @bill_pay, :html => { :class => 'form-horizontal' } do |f| %>
    <%= f.association :bill %>

  <%= f.input :name %>
  <%= f.input :bill_no %>
  <%= f.input :bill_amount %>
  <%= f.input :bill_due_date %>
  <br>
  <%= f.file_field :photo,:class => "pull-right" %>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                bill_pays_path, :class => 'btn' %>
  </div>
<% end %>

app/views/bill_pays/edit.html.erb
<%- model_class = BillPay -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bill_pays/index.html.erb
<%- model_class = BillPay -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_bill_pay_path,
            :class => 'btn btn-primary' %>

            <hr>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:bill_no) %></th>
      <th><%= model_class.human_attribute_name(:bill_amount) %></th>
      <th><%= model_class.human_attribute_name(:bill_due_date) %></th>
      <th><%= model_class.human_attribute_name(:bill_id) %></th>
      <th><%= model_class.human_attribute_name(:photo) %></th>
    
      <th><%= model_class.human_attribute_name(:created_at) %></th>

    </tr>
  </thead>
  <tbody>
    <% @bill_pays.each do |bill_pay| %>
      <tr>
        <td><%= link_to bill_pay.id, bill_pay_path(bill_pay) %></td>
        <td><%= bill_pay.name %></td>
        <td><%= bill_pay.bill_no %></td>
        <td><%= bill_pay.bill_amount %></td>
        <td><%= bill_pay.bill_due_date %></td>
        <td><%= bill_pay.bill_id %></td>
        <td>   <%= image_tag bill_pay.photo.url(:small) %>
</td>
        <td><%=l bill_pay.created_at %></td>
        <td>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bill_pays/new.html.erb
<%- model_class = BillPay -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bill_pays/show.html.erb
<%- model_class = BillPay -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @bill_pay.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bill_no) %>:</strong></dt>
  <dd><%= @bill_pay.bill_no %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bill_amount) %>:</strong></dt>
  <dd><%= @bill_pay.bill_amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bill_due_date) %>:</strong></dt>
  <dd><%= @bill_pay.bill_due_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bill_id) %>:</strong></dt>
  <dd><%= @bill_pay.bill_id %></dd>
  <hr>
   <%= image_tag @bill_pay.photo.url(:small) %>

</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              bill_pays_path, :class => 'btn'  %>

</div>