config/routes.rb
Mjservices::Application.routes.draw do
  resources :bill_pays

  resources :bills

  devise_for :users

  resources :bill_accounts

  resources :bill_services

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  attr_accessible :account_number, :bill_address, :name, :nameonbill, :provider, :user_id
  attr_accessible :photo
  #relations 
  belongs_to :user
    has_many :bill_pays
	

  has_attached_file :photo, :styles => { :small => "150x150>" },
                  :url  => "/assets/bills/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/bills/:id/:style/:basename.:extension"

	validates_attachment_presence :photo
	validates_attachment_size :photo, :less_than => 10.megabytes
	validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']



end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bills }
    end
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
    @bill = Bill.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bill }
    end
  end

  # GET /bills/new
  # GET /bills/new.json
  def new
    @bill = Bill.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bill }
    end
  end

  # GET /bills/1/edit
  def edit
    @bill = Bill.find(params[:id])
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(params[:bill])

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render json: @bill, status: :created, location: @bill }
      else
        format.html { render action: "new" }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bills/1
  # PUT /bills/1.json
  def update
    @bill = Bill.find(params[:id])

    respond_to do |format|
      if @bill.update_attributes(params[:bill])
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill = Bill.find(params[:id])
    @bill.destroy

    respond_to do |format|
      format.html { redirect_to bills_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<%= simple_form_for @bill, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :account_number %>
  <%= f.input :nameonbill %>
  <%= f.input :bill_address %>
  <%= f.input :provider %>
  <% f.input :user_id %>

  <%= f.file_field :photo ,:class => "pull-right"%>
    <hr> 
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                bills_path, :class => 'btn' %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<%- model_class = Bill -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bills/index.html.erb
<%- model_class = Bill -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:account_number) %></th>
      <th><%= model_class.human_attribute_name(:nameonbill) %></th>
      <th><%= model_class.human_attribute_name(:bill_address) %></th>
      <th><%= model_class.human_attribute_name(:provider) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:photo) %></th>
     
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= link_to bill.id, bill_path(bill) %></td>
        <td><%= bill.name %></td>
        <td><%= bill.account_number %></td>
        <td><%= bill.nameonbill %></td>
        <td><%= bill.bill_address %></td>
        <td><%= bill.provider %></td>
        <td><%= bill.user_id %></td>
    <td><%= image_tag bill.photo.url(:small) %></td>
        <td><%=l bill.created_at %></td>
        <td>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_bill_path,
            :class => 'btn btn-primary' %>

app/views/bills/new.html.erb
<%- model_class = Bill -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bills/show.html.erb
<%- model_class = Bill -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @bill.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:account_number) %>:</strong></dt>
  <dd><%= @bill.account_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nameonbill) %>:</strong></dt>
  <dd><%= @bill.nameonbill %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bill_address) %>:</strong></dt>
  <dd><%= @bill.bill_address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:provider) %>:</strong></dt>
  <dd><%= @bill.provider %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @bill.user_id %></dd>
  <hr>
 <%= image_tag @bill.photo.url(:small) %>

</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              bills_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bill_path(@bill), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bill_path(@bill),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>