config/routes.rb
Mjservices::Application.routes.draw do
  resources :bill_pays

  resources :bills

  devise_for :users

  resources :bill_accounts

  resources :bill_services

end

app/models/bill_service.rb
class BillService < ActiveRecord::Base
  attr_accessible :account_no, :bill_address, :bill_amount, :bill_description, :bill_due_date, :bill_no, :category, :name_on_bill, :where_to_pay
  attr_accessible :bill_account_id
  belongs_to :bill_account
end

app/controllers/bill_services_controller.rb
class BillServicesController < ApplicationController
  # GET /bill_services
  # GET /bill_services.json
  def index
    @bill_services = BillService.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bill_services }
    end
  end

  # GET /bill_services/1
  # GET /bill_services/1.json
  def show
    @bill_service = BillService.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bill_service }
    end
  end

  # GET /bill_services/new
  # GET /bill_services/new.json
  def new
    @bill_service = BillService.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bill_service }
    end
  end

  # GET /bill_services/1/edit
  def edit
    @bill_service = BillService.find(params[:id])
  end

  # POST /bill_services
  # POST /bill_services.json
  def create
    @bill_service = BillService.new(params[:bill_service])

    respond_to do |format|
      if @bill_service.save
        format.html { redirect_to @bill_service, notice: 'Bill service was successfully created.' }
        format.json { render json: @bill_service, status: :created, location: @bill_service }
      else
        format.html { render action: "new" }
        format.json { render json: @bill_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bill_services/1
  # PUT /bill_services/1.json
  def update
    @bill_service = BillService.find(params[:id])

    respond_to do |format|
      if @bill_service.update_attributes(params[:bill_service])
        format.html { redirect_to @bill_service, notice: 'Bill service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bill_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bill_services/1
  # DELETE /bill_services/1.json
  def destroy
    @bill_service = BillService.find(params[:id])
    @bill_service.destroy

    respond_to do |format|
      format.html { redirect_to bill_services_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bill_services_helper.rb
module BillServicesHelper
end

app/views/bill_services/_form.html.erb
<%= simple_form_for @bill_service, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :category %>
  <%= f.input :bill_description %>
  <%= f.input :bill_no %>
  <%= f.input :name_on_bill %>
  <%= f.input :bill_address %>
  <%= f.input :account_no %>
  <%= f.input :bill_amount %>
  <%= f.input :bill_due_date %>
  <%= f.input :where_to_pay %>
  <%= f.input :bill_account_id %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                bill_services_path, :class => 'btn' %>
  </div>
<% end %>

app/views/bill_services/edit.html.erb
<%- model_class = BillService -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bill_services/index.html.erb
<%- model_class = BillService -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:category) %></th>
      <th><%= model_class.human_attribute_name(:bill_description) %></th>
      <th><%= model_class.human_attribute_name(:bill_no) %></th>
      <th><%= model_class.human_attribute_name(:name_on_bill) %></th>
      <th><%= model_class.human_attribute_name(:bill_address) %></th>
      <th><%= model_class.human_attribute_name(:account_no) %></th>
      <th><%= model_class.human_attribute_name(:bill_amount) %></th>
      <th><%= model_class.human_attribute_name(:bill_due_date) %></th>
      <th><%= model_class.human_attribute_name(:where_to_pay) %></th>
      <th><%= model_class.human_attribute_name(:bill_account_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @bill_services.each do |bill_service| %>
      <tr>
        <td><%= link_to bill_service.id, bill_service_path(bill_service) %></td>
        <td><%= bill_service.category %></td>
        <td><%= bill_service.bill_description %></td>
        <td><%= bill_service.bill_no %></td>
        <td><%= bill_service.name_on_bill %></td>
        <td><%= bill_service.bill_address %></td>
        <td><%= bill_service.account_no %></td>
        <td><%= bill_service.bill_amount %></td>
        <td><%= bill_service.bill_due_date %></td>
        <td><%= bill_service.where_to_pay %></td>
        <td><%= bill_service.bill_account_id %></td>
        <td><%=l bill_service.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_bill_service_path(bill_service), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      bill_service_path(bill_service),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_bill_service_path,
            :class => 'btn btn-primary' %>

app/views/bill_services/new.html.erb
<%- model_class = BillService -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bill_services/show.html.erb
<%- model_class = BillService -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:category) %>:</strong></dt>
  <dd><%= @bill_service.category %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bill_description) %>:</strong></dt>
  <dd><%= @bill_service.bill_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bill_no) %>:</strong></dt>
  <dd><%= @bill_service.bill_no %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name_on_bill) %>:</strong></dt>
  <dd><%= @bill_service.name_on_bill %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bill_address) %>:</strong></dt>
  <dd><%= @bill_service.bill_address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:account_no) %>:</strong></dt>
  <dd><%= @bill_service.account_no %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bill_amount) %>:</strong></dt>
  <dd><%= @bill_service.bill_amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bill_due_date) %>:</strong></dt>
  <dd><%= @bill_service.bill_due_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:where_to_pay) %>:</strong></dt>
  <dd><%= @bill_service.where_to_pay %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bill_account_id) %>:</strong></dt>
  <dd><%= @bill_service.bill_account_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              bill_services_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bill_service_path(@bill_service), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bill_service_path(@bill_service),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>