config/routes.rb
Mjservices::Application.routes.draw do
  resources :bill_pays

  resources :bills

  devise_for :users

  resources :bill_accounts

  resources :bill_services

end

app/models/bill_account.rb
class BillAccount < ActiveRecord::Base
  attr_accessible :account_no, :description, :name, :name_on_the_bill
    attr_accessible :provider

  attr_accessible :user_id
  belongs_to :user

  has_many :bill_services
end

app/controllers/bill_accounts_controller.rb
class BillAccountsController < ApplicationController
  # GET /bill_accounts
  # GET /bill_accounts.json
  def index
    @bill_accounts = BillAccount.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bill_accounts }
    end
  end

  # GET /bill_accounts/1
  # GET /bill_accounts/1.json
  def show
    @bill_account = BillAccount.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bill_account }
    end
  end

  # GET /bill_accounts/new
  # GET /bill_accounts/new.json
  def new
    @bill_account = BillAccount.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bill_account }
    end
  end

  # GET /bill_accounts/1/edit
  def edit
    @bill_account = BillAccount.find(params[:id])
  end

  # POST /bill_accounts
  # POST /bill_accounts.json
  def create
    @bill_account = BillAccount.new(params[:bill_account])

    respond_to do |format|
      if @bill_account.save
        format.html { redirect_to @bill_account, notice: 'Bill account was successfully created.' }
        format.json { render json: @bill_account, status: :created, location: @bill_account }
      else
        format.html { render action: "new" }
        format.json { render json: @bill_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bill_accounts/1
  # PUT /bill_accounts/1.json
  def update
    @bill_account = BillAccount.find(params[:id])

    respond_to do |format|
      if @bill_account.update_attributes(params[:bill_account])
        format.html { redirect_to @bill_account, notice: 'Bill account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bill_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bill_accounts/1
  # DELETE /bill_accounts/1.json
  def destroy
    @bill_account = BillAccount.find(params[:id])
    @bill_account.destroy

    respond_to do |format|
      format.html { redirect_to bill_accounts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bill_accounts_helper.rb
module BillAccountsHelper
end

app/views/bill_accounts/_form.html.erb
<%= simple_form_for @bill_account, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :account_no %>
  <%= f.input :name_on_the_bill %>
  <%= f.input :description %>
  <%= f.input :user_id %>
  <%= f.input :provider %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                bill_accounts_path, :class => 'btn' %>
  </div>
<% end %>

app/views/bill_accounts/edit.html.erb
<%- model_class = BillAccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bill_accounts/index.html.erb
<%- model_class = BillAccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:account_no) %></th>
      <th><%= model_class.human_attribute_name(:name_on_the_bill) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:provider) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @bill_accounts.each do |bill_account| %>
      <tr>
        <td><%= link_to bill_account.id, bill_account_path(bill_account) %></td>
        <td><%= bill_account.name %></td>
        <td><%= bill_account.account_no %></td>
        <td><%= bill_account.name_on_the_bill %></td>
        <td><%= bill_account.description %></td>
        <td><%= bill_account.user_id %></td>
        <td><%= bill_account.provider %></td>
        <td><%=l bill_account.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_bill_account_path(bill_account), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      bill_account_path(bill_account),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_bill_account_path,
            :class => 'btn btn-primary' %>

app/views/bill_accounts/new.html.erb
<%- model_class = BillAccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bill_accounts/show.html.erb
<%- model_class = BillAccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @bill_account.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:account_no) %>:</strong></dt>
  <dd><%= @bill_account.account_no %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name_on_the_bill) %>:</strong></dt>
  <dd><%= @bill_account.name_on_the_bill %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @bill_account.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @bill_account.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:provider) %>:</strong></dt>
  <dd><%= @bill_account.provider %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              bill_accounts_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bill_account_path(@bill_account), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bill_account_path(@bill_account),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>